version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
  
formats:
  - pdf
  - epub

latex:
  packages:
    - texlive-xetex
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-lang-vietnamese
